package com.primb.rxtest.weather.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.primb.rxtest.weather.module.CityBean;
import com.primb.rxtest.weather.module.ProvinceBean;

import com.primb.rxtest.weather.dao.CityBeanDao;
import com.primb.rxtest.weather.dao.ProvinceBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig cityBeanDaoConfig;
    private final DaoConfig provinceBeanDaoConfig;

    private final CityBeanDao cityBeanDao;
    private final ProvinceBeanDao provinceBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        cityBeanDaoConfig = daoConfigMap.get(CityBeanDao.class).clone();
        cityBeanDaoConfig.initIdentityScope(type);

        provinceBeanDaoConfig = daoConfigMap.get(ProvinceBeanDao.class).clone();
        provinceBeanDaoConfig.initIdentityScope(type);

        cityBeanDao = new CityBeanDao(cityBeanDaoConfig, this);
        provinceBeanDao = new ProvinceBeanDao(provinceBeanDaoConfig, this);

        registerDao(CityBean.class, cityBeanDao);
        registerDao(ProvinceBean.class, provinceBeanDao);
    }
    
    public void clear() {
        cityBeanDaoConfig.getIdentityScope().clear();
        provinceBeanDaoConfig.getIdentityScope().clear();
    }

    public CityBeanDao getCityBeanDao() {
        return cityBeanDao;
    }

    public ProvinceBeanDao getProvinceBeanDao() {
        return provinceBeanDao;
    }

}
